services:
    idci_simplemedia.manager:
        class: IDCI\Bundle\SimpleMediaBundle\Service\Manager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

    idci_simplemedia.twig.simplemedia_extension:
        class: IDCI\Bundle\SimpleMediaBundle\Twig\SimpleMediaExtension
        arguments: ["@idci_simplemedia.manager"]
        tags:
            - { name: twig.extension }

    idci_simplemedia.type.mediatag:
        class: IDCI\Bundle\SimpleMediaBundle\Form\Type\MediaTagType
        arguments: ["@idci_simplemedia.manager"]
        tags:
            - { name: form.type, alias: media_tag }
